# Generated by Django 4.1.4 on 2022-12-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('job_vacancy', models.CharField(default='', max_length=255)),
                ('job_category', models.CharField(default='', max_length=255)),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('employee_email', models.EmailField(default='', max_length=255, verbose_name='Email')),
                ('employee_website', models.CharField(default='', max_length=255, verbose_name='Website/link', null=True)),
                ('employee_cv', models.FileField(upload_to='', verbose_name='Upload your Resume here')),
                ('employee_coverletter', models.CharField(default='', max_length=255, verbose_name='Coverletter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.submitjob')),
            ],
        ),
    ]
