# Generated by Django 4.1.4 on 2022-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitjob',
            name='job_description',
            field=models.CharField(default='', max_length=255, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='time_employment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
