# Generated by Django 4.1.4 on 2022-12-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_submitjob_job_description_submitjob_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitjob',
            name='company_img',
            field=models.ImageField(default='', upload_to='', verbose_name='Company Image'),
        ),
    ]
