# Generated by Django 4.1.4 on 2022-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_submitjob_company_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='company_img',
            field=models.ImageField(default='', upload_to='', verbose_name='Company Image'),
        ),
    ]
