# Generated by Django 4.1.4 on 2022-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_submitjob_company_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitjob',
            name='job_qualification',
            field=models.CharField(default='', max_length=255, verbose_name='Job Qualification'),
        ),
    ]
