# Generated by Django 4.1.4 on 2023-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_submitjob_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='employee_website',
            field=models.CharField(default='', max_length=255, verbose_name='Website/link'),
        ),
    ]
